Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2019-07, with the labels that each got.

#18 Add findengine.bat
  BuildProject.bat
  FindEngine.bat
  LaunchClient.bat
  LaunchServer.bat
Labels: jira/no-ticket, size/M

#20 UNR-1717 added missing role check
  Game/Source/GDKShooter/Private/Characters/Components/GDKMovementComponent.cpp
Labels: jira/UNR, size/XS

#22 Update scripts to latest versions
  BuildProject.bat
  DeployGame.bat
  FindEngine.bat
  LaunchClient.bat
  LaunchServer.bat
Labels: jira/no-ticket, size/M

#23 Remove quotes from engine path
  LaunchClient.bat
  LaunchServer.bat
Labels: jira/no-ticket, size/XS

#24 Stop service button shouldn't be there by default
  Game/Config/DefaultSpatialGDKEditorSettings.ini
Labels: jira/no-ticket, size/XS

#26 Bugfix/UNR-1789/allow-map-override-in-shipping
  Game/Source/GDKShooter.Target.cs
Labels: jira/UNR, size/XS

#31 Feature/sim players enhancements
  Game/Content/AI/BB_NPC.uasset
  Game/Content/AI/BT_Wander.uasset
  Game/Content/AI/Services/BTService_RandomLocation.uasset
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
  Game/Content/Characters/SimulatedPlayer/SimulatedPlayerAiController_BP.uasset
  Game/Content/Characters/SimulatedPlayer/SimulatedPlayerCharacter_BP.uasset
  Game/Content/Controllers/BP_SimulatedPlayerAIController.uasset
  Game/Content/GameMode/BP_CorridorGameMode.uasset
  Game/Content/GameMode/BP_DeathmatchGameMode.uasset
  Game/Content/GameMode/BP_DeploymentGameMode.uasset
  Game/Content/GameMode/BP_GymGameMode.uasset
Labels: jira/no-ticket, size/XS

#28 Sim players!
  BuildProject.bat
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/AI/BB_NPC.uasset
  Game/Content/AI/BT_Wander.uasset
  Game/Content/AI/Services/BTService_RandomLocation.uasset
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
  Game/Content/Characters/SimulatedPlayer/SimulatedPlayerBehaviorTree_BP.uasset
  Game/Content/Characters/SimulatedPlayer/SimulatedPlayerBlackboard_BP.uasset
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/Controllers/BP_SimulatedPlayerAIController.uasset
  Game/Content/GameMode/BP_CorridorGameMode.uasset
  Game/Content/GameMode/BP_DeathmatchGameMode.uasset
  Game/Content/GameMode/BP_DeploymentGameMode.uasset
  Game/Content/GameMode/BP_GymGameMode.uasset
  Game/Content/Maps/FPS-Start_Medium.umap
  Game/Content/Maps/FPS-Start_Medium_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Tiny.umap
  Game/Content/Maps/FPS-Start_Tiny_BuiltData.uasset
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
Labels: jira/no-ticket, size/M

#34 Bugfix/better sim movement
  Game/Content/AI/BT_Wander.uasset
  Game/Content/AI/Services/BTService_RandomLocation.uasset
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
  Game/Content/Maps/FPS-Start_Tiny.umap
  Game/Content/Maps/FPS-Start_Tiny_BuiltData.uasset
Labels: jira/no-ticket, size/XS

#35 Feature/fix memory leaks
  .gitignore
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Private/Game/GDKShooterSpatialGameInstance.cpp
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchScoreComponent.h
Labels: jira/no-ticket, size/S

#36 UNR-1836: Sim players now join the game even if the round has started
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
Labels: jira/UNR, size/XS

#37 fix log message crashing by trying to access int value as a memory pointer instead of printing it
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
Labels: jira/no-ticket, size/XS
