Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2019-12, with the labels that each got.

#80 Update spatialos.json
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS

#82 first fixes for iOS
  Game/Config/DefaultEngine.ini
  Game/Content/UI/Blueprints/BP_QuitButton.uasset
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
Labels: jira/no-ticket, size/XS

#84 Merge 0.8.0 Preview into Master
  .buildkite/nightly.steps.yaml
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchSpawnerComponent.h
  ci/deploy.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
  ci/setup-and-build.ps1
  ci/slack-notify.ps1
Labels: jira/no-ticket, size/L

#85 Update to 14.3
  Game/Config/DefaultSpatialGDKSettings.ini
  spatial/spatialos.json
Labels: jira/no-ticket, size/S

#86 Update DeploymentSnapshotTemplate.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentSnapshotTemplate.cpp
Labels: jira/no-ticket, size/XS
