Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2019-08, with the labels that each got.

#39 Add command line cheats to set lobby and match timers
  Game/Source/GDKShooter/Private/Game/Components/LobbyTimerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/MatchTimerComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/MatchTimerComponent.h
Labels: jira/no-ticket, size/S

#41 Convert InformPlayerCount into a CrossServer RPC
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
  Game/Source/GDKShooter/Private/Game/Components/LobbyTimerComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/LobbyTimerComponent.h
Labels: jira/no-ticket, size/XS

#43 DOC-1255 Clarify elements of the GDK in readme
  README.md
Labels: jira/DOC, size/S

#44 Add two_worker_test for tutorial
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/M

#45 Disable offloading by default UNR-1886
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/UNR, size/XS

#46 [UNR-1888] Bugfix: Guns were not being attached to players sometimes
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
Labels: jira/UNR, size/XS

#48 0.6.1 hotfix
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  README.md
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/M

#49 0.6.1 hotfix
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  README.md
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/M

#50 0.61-hotifx > master
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  README.md
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/M

#51 New splash image
  Game/Content/Splash/EdSplash.bmp
  Game/Content/Splash/Splash.bmp
Labels: jira/no-ticket, size/XS
