Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2019-09, with the labels that each got.

#52 Fixed crashes when running new tests
  Game/Plugins/ExampleProjectTests/Source/ExampleProjectTests/Private/SpatialAutomationCommon.cpp
  Game/Plugins/ExampleProjectTests/Source/ExampleProjectTests/Private/Spawning/SpawningCommon.cpp
  Game/Plugins/ExampleProjectTests/Source/ExampleProjectTests/Public/Spawning/SpawningCommon.h
  Game/Source/GDKShooter/Private/Testing/TestingObject.cpp
Labels: jira/no-ticket, size/S

#53 UNR 1863: Update Database Integrations Example Project - Start Branch
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchScoreComponent.h
  Game/Source/GDKShooter/Public/Game/Components/ScorePublisher.h
Labels: jira/no-ticket, size/S

#54 UNR-1863: Update Database Integrations Example Project - Finish Branch
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchScoreComponent.h
  Game/Source/GDKShooter/Public/Game/Components/ScorePublisher.h
Labels: jira/UNR, size/M

#57 UNR-2019: Example Project CI
  .buildkite/nightly.definition.yaml
  .buildkite/nightly.steps.yaml
  Game/Source/GDKShooter.Target.cs
  ci/common.ps1
  ci/deploy.ps1
  ci/setup-and-build.ps1
Labels: jira/UNR, size/XL

#55 Feature: CrashBot_Gym fixes for Offloading Tutorial
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Blueprints/Weapons/BP_Crashbot_Rifle.uasset
  Game/Content/Characters/BP_CrashBot.uasset
  Game/Content/Characters/BP_CrashBot_PlacedInWorld.uasset
  Game/Content/Controllers/BP_CrashBotController.uasset
  Game/Content/Maps/CrashBot_Gym.umap
  Game/Content/Maps/Offloading_Gym.umap
  Game/Content/Maps/Offloading_Gym_BuiltData.uasset
  Game/Source/GDKShooter/Private/Characters/Components/ShootingComponent.cpp
  spatial/workers/unreal/spatialos.AIWorker.worker.json
  spatial/workers/unreal/spatialos.CrashBotWorker.worker.json
Labels: jira/no-ticket, size/L

#58 [UNR-2093] Upgrade to SpatialOS 14.1.0
  Game/Source/GDKShooter/Private/Deployments/DeploymentSnapshotTemplate.cpp
  Game/Source/GDKShooter/Private/Game/Components/SpatialSessionStateComponent.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentSnapshotTemplate.h
  spatial/spatialos.json
Labels: jira/UNR, size/S

#61 Extend CI Slack output
  ci/deploy.ps1
Labels: jira/no-ticket, size/XS

#59 UNR 2168: Remove QBI toggle
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/workers/deployment-manager/spatialos.DeploymentManager.worker.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/UNR, size/M
