Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2019-11, with the labels that each got.

#68 Feature/unr 2101 allow scheduled builds
  .buildkite/nightly.steps.yaml
Labels: jira/UNR, size/XS

#69 Task/unr 1905 improve slack hooks
  ci/deploy.ps1
Labels: jira/UNR, size/M

#71 Truncate long build messages in Slack notifications
  ci/deploy.ps1
Labels: jira/UNR, size/XS

#67 Increase default session duration from 5min to 2hours
  Game/Source/GDKShooter/Public/Game/Components/TimerComponent.h
Labels: jira/no-ticket, size/XS

#73 Reduce default session timer from 15 seconds to 3 seconds
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
Labels: jira/no-ticket, size/XS

#72 make slack message pretty
  ci/deploy.ps1
Labels: jira/UNR, size/XS

#74 Bugfix/unr 1905 truncate string correctly
  ci/deploy.ps1
Labels: jira/UNR, size/XS

#75 v4-2019-11-07-bk3700-fbffad576b9676d7
  .buildkite/nightly.steps.yaml
Labels: jira/UNR, size/XS

#76 [GV-115] Enable multiple engines in CI with Example Project
  .buildkite/nightly.steps.yaml
  ci/deploy.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
  ci/setup-and-build.ps1
  ci/slack-notify.ps1
Labels: jira/GV, size/L

#79 [UNR-2425][MS] Adding SimPlayer scripts
  Launch10SimPlayerClients.bat
  LaunchSimPlayerClient.bat
Labels: jira/UNR, size/S

#77 [UNR-2425][MS] Fixing bug with sim players not moving.
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchSpawnerComponent.h
Labels: jira/UNR, size/XS
