Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-03, with the labels that each got.

#108 Merge of MBL-19
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
Labels: jira/MBL, size/M

#109 [UNR-3016] Maybe fix Slack hooks?
  ci/common.ps1
Labels: jira/UNR, size/XS

#111 [CHINF-886][MS] Fixing a crash caused by the merge into release related to the jira issue.
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
Labels: jira/CHINF, size/XS

#110 UNR-2965 Remove rename of FBuild.exe
  ci/setup-and-build.ps1
Labels: jira/UNR, size/XS

#112 [UNR-3041][MS] Addin 14.3 into release
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#105 Enable DDC
  Game/Config/DefaultEngine.ini
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/S

#114 [UNR-3044][MS] Fixing crash when clicking cancel button
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
Labels: jira/UNR, size/S

#116 [UNR-3071][MS] Update Worker SDK version
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#118 0.8.1 preview rc > preview
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  Game/Content/GameMode/BP_PlayerState.uasset
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
  Game/Source/GDKShooter/Public/Controllers/GDKPlayerController.h
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
  Game/Source/GDKShooter/Public/Game/Components/PlayerPublisher.h
  README.md
  spatial/spatialos.json
Labels: jira/no-ticket, size/L

#119 preview > release
  .buildkite/nightly.definition.yaml
  .buildkite/nightly.steps.yaml
  FindEngine.bat
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
  Game/Content/GameMode/BP_PlayerState.uasset
  Game/Content/Splash/EdSplash.bmp
  Game/Content/Splash/Splash.bmp
  Game/Source/GDKShooter.Target.cs
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentSnapshotTemplate.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/Game/Components/LobbyTimerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/MatchTimerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/SpatialSessionStateComponent.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
  Game/Source/GDKShooter/Public/Controllers/GDKPlayerController.h
  Game/Source/GDKShooter/Public/Deployments/DeploymentSnapshotTemplate.h
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchSpawnerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/LobbyTimerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/MatchTimerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/PlayerPublisher.h
  Game/Source/GDKShooter/Public/Game/Components/TimerComponent.h
  README.md
  ci/common.ps1
  ci/deploy.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
  ci/setup-and-build.ps1
  ci/slack-notify.ps1
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/spatialos.json
  spatial/workers/deployment-manager/spatialos.DeploymentManager.worker.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/XXL

#121 Release 0.8.1 master merge
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
  README.md
  spatial/spatialos.json
Labels: jira/no-ticket, size/M

#122 4.24 support
  Game/Content/Blueprints/MapBuilder/BP_MapBuilder.uasset
  Game/Content/Maps/FPS-Start_Tiny.umap
  Game/GDKShooter.uproject
  Game/Source/GDKShooter/GDKShooter.Build.cs
  Game/Source/GDKShooter/Private/Characters/Components/EquippedComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/FirstPersonTraceProvider.cpp
  Game/Source/GDKShooter/Private/Characters/Components/GDKMovementComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/HealthComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/MetaDataComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/ShootingComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/TeamComponent.cpp
  Game/Source/GDKShooter/Private/Characters/GDKCharacter.cpp
  Game/Source/GDKShooter/Private/Controllers/Components/ControllerEventsComponent.cpp
  Game/Source/GDKShooter/Private/Controllers/Components/TeamSettingComponent.cpp
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentSnapshotTemplate.cpp
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Private/GDKLogging.cpp
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchSpawnerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/LobbyTimerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/MatchStateComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/MatchTimerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/PlayerCountingComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/SpatialSessionStateComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/SpawnRequestPublisher.cpp
  Game/Source/GDKShooter/Private/Game/Components/TeamSpawnerComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/TimerComponent.cpp
  Game/Source/GDKShooter/Private/GameFramework/CrossServerPawn.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
  Game/Source/GDKShooter/Private/Weapons/Holdable.cpp
  Game/Source/GDKShooter/Private/Weapons/InstantWeapon.cpp
  Game/Source/GDKShooter/Private/Weapons/Projectile.cpp
  Game/Source/GDKShooter/Private/Weapons/ProjectileWeapon.cpp
  Game/Source/GDKShooter/Private/Weapons/Weapon.cpp
  Game/Source/GDKShooter/Public/Characters/GDKCharacter.h
  Game/Source/GDKShooter/Public/Weapons/Holdable.h
  Game/Source/GDKShooter/Public/Weapons/Weapon.h
  Game/Source/GDKShooterEditor.Target.cs
Labels: jira/no-ticket, size/L

#124 Merging changes from 0.8.1 blueprints
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
Labels: jira/no-ticket, size/XS

#125 Use 2019 build queue
  .buildkite/nightly.steps.yaml
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/XS

#127 [UNR-2944][MS] Removing CrossServerPawn
  Game/Source/GDKShooter/Private/GameFramework/CrossServerPawn.cpp
  Game/Source/GDKShooter/Public/GameFramework/CrossServerPawn.h
Labels: jira/UNR, size/M

#126 Switch to 4.24 for now
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/XS

#131 [UNR-3194][MS] Adding back cross server pawn.
  Game/Source/GDKShooter/Private/GameFramework/CrossServerPawn.cpp
  Game/Source/GDKShooter/Public/GameFramework/CrossServerPawn.h
Labels: jira/UNR, size/M

#132 Use VS2019 and WinServer2019 build queue
  .buildkite/nightly.steps.yaml
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/XS
