Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-05, with the labels that each got.

#143 updating matchfile & fastlane plugin
  ci/nightly.template.steps.yaml
  fastlane/Matchfile
Labels: jira/no-ticket, size/XS

#148 Create UnrealGDKVersion.txt
  UnrealGDKVersion.txt
Labels: jira/no-ticket, size/XS

#151 Remove DeploymentManager from one_worker_test.json
  spatial/one_worker_test.json
Labels: jira/no-ticket, size/XS

#152 0.9.0 master merge
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/XS

#146 [UNR-3396] Team Deathmatch
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
  Game/Content/Characters/Components/BP_FloatingCombatText.uasset
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_DeathmatchGameState.uasset
  Game/Content/GameMode/BP_PlayerState.uasset
  Game/Content/GameMode/BP_TeamDeathmatchGameMode.uasset
  Game/Content/GameMode/BP_TeamDeathmatchGameState.uasset
  Game/Content/Maps/FPS-Start_Tiny.umap
  Game/Content/Maps/FPS-Start_Tiny_BuiltData.uasset
  Game/Content/UI/Blueprints/BP_HUD_TeamDeathmatch.uasset
  Game/Content/UI/Blueprints/BP_TeamDeathmatch_LoginScreen.uasset
  Game/Content/UI/Blueprints/Scores/BP_GDKTeamDeathmatchScoreboard.uasset
  Game/Content/UI/Blueprints/Scores/BP_ScoreTableWidget.uasset
  Game/Content/UI/Blueprints/Scores/BP_TeamScoreTable.uasset
  Game/Source/GDKShooter/Private/Characters/Components/HealthComponent.cpp
  Game/Source/GDKShooter/Private/Characters/Components/TeamComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchSpawnerComponent.cpp
  Game/Source/GDKShooter/Private/UI/GDKWidget.cpp
  Game/Source/GDKShooter/Public/Characters/Components/HealthComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/TeamComponent.h
  Game/Source/GDKShooter/Public/Game/Components/ScorePublisher.h
  Game/Source/GDKShooter/Public/Game/Components/TeamDeathmatchScoreComponent.h
  Game/Source/GDKShooter/Public/Game/Components/TeamDeathmatchSpawnerComponent.h
  Game/Source/GDKShooter/Public/UI/GDKWidget.h
Labels: jira/UNR, size/XL

#154 [UNR-2908] Update CI command for Schema generation
  ci/setup-and-build.ps1
Labels: jira/UNR, size/S

#155 [UNR-3397] Control game mode
  Game/Content/Blueprints/BP_ControlPoint.uasset
  Game/Content/Blueprints/Enum_ControlPointState.uasset
  Game/Content/Environment/Props/Materials/M_ControlPoint.uasset
  Game/Content/Environment/TeamPlayerStart.uasset
  Game/Content/GameMode/BP_ControlGameMode.uasset
  Game/Content/GameMode/BP_ControlGameState.uasset
  Game/Content/GameMode/BP_TeamDeathmatchGameState.uasset
  Game/Content/UI/Blueprints/BP_ControlPointProgress.uasset
  Game/Content/UI/Blueprints/BP_GDK_HUD.uasset
  Game/Content/UI/Blueprints/BP_HUD_Control.uasset
  Game/Content/UI/Blueprints/BP_PlayerHUD_Control.uasset
  Game/Content/UI/Blueprints/Scores/BP_TeamScoreTable.uasset
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchSpawnerComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/TeamDeathmatchScoreComponent.h
  Game/Source/GDKShooter/Public/Game/Components/TeamDeathmatchSpawnerComponent.h
Labels: jira/UNR, size/M

#156 [UNR-3400] Add map for Control game mode.
  .gitignore
  Game/Content/Blueprints/BP_ControlPoint.uasset
  Game/Content/Blueprints/MapBuilder/Tiles/Misc/BP_Tile_Structure_Tower_A.uasset
  Game/Content/GameMode/BP_ControlGameState.uasset
  Game/Content/Maps/Control_Medium.umap
  Game/Content/Maps/Corridor_Gym_BuiltData.uasset
  Game/Content/Maps/CrashBot_Gym_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Large_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Large_Limited_Spawns_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Medium_BuiltData.uasset
  Game/Content/Maps/FPS-Start_SmallTown_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Small_BuiltData.uasset
  Game/Content/Maps/FPS-Start_Tiny_BuiltData.uasset
  Game/Content/Maps/FPS_Test_Gym_01_BuiltData.uasset
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchSpawnerComponent.cpp
  Game/Source/GDKShooter/Public/Game/Components/TeamDeathmatchSpawnerComponent.h
  ci/deploy.ps1
Labels: jira/UNR, size/S

#157 Remove Deployments map
  Game/Config/DefaultEngine.ini
  Game/Content/Controllers/BP_DeploymentController.uasset
  Game/Content/GameMode/BP_DeploymentGameMode.uasset
  Game/Content/Maps/Deployments.umap
  Game/Content/UI/Blueprints/Deployments/BP_GDKDeploymentWidget.uasset
  Game/Content/UI/Blueprints/Deployments/BP_HUD_Deployments.uasset
  Game/Content/UI/Blueprints/Deployments/BP_Loading.uasset
  Game/Content/UI/Blueprints/Deployments/BP_LobbyScreen.uasset
  Game/Content/UI/Textures/UI_T_Text_Back.uasset
  Game/Content/UI/Textures/UI_T_Text_Browse.uasset
  Game/Content/UI/Textures/UI_T_Text_Connecting.uasset
  Game/Content/UI/Textures/UI_T_Text_Connection_Failed.uasset
  Game/Content/UI/Textures/UI_T_Text_Enter_Your_Name_Here.uasset
  Game/Content/UI/Textures/UI_T_Text_Join.uasset
  Game/Content/UI/Textures/UI_T_Text_Join_Game.uasset
  Game/Content/UI/Textures/UI_T_Text_Joining_Deployment.uasset
  Game/Content/UI/Textures/UI_T_Text_Player_Spawn_Failed.uasset
  Game/Content/UI/Textures/UI_T_Text_Press_Space_To_Connect.uasset
  Game/Content/UI/Textures/UI_T_Text_Press_Space_To_Retry.uasset
  Game/Content/UI/Textures/UI_T_Text_Quick_Join.uasset
  Game/Content/UI/Textures/UI_T_Text_Ready_To_Connect.uasset
  Game/Content/UI/Textures/UI_T_Text_Worker_Disconnected.uasset
  Game/Content/UI/Textures/UI_T_Text_You_Have_Died.uasset
  Game/Content/UI/Textures/UI_T_Title_Deployment_List.uasset
  Game/Content/UI/Textures/UI_T_Title_Matchmaking.uasset
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
Labels: jira/no-ticket, size/L
