Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-08, with the labels that each got.

#197 UE 4.25 for example project
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/XS

#208 UNR-3925: Use valid ip address
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
Labels: jira/UNR, size/XS

#209 changing match time to 120 minutes instead of 20 minutes
  Game/Content/GameMode/BP_ControlGameState.uasset
Labels: jira/no-ticket, size/XS

#195 buildkite nightly pipeline for UnrealGDKExampleProject Mobile Platform Automatic Test on Firebase UNR-3268
  .buildkite/nightly.steps.yaml
  ci/change-runtime-settings.py
  ci/common.py
  ci/deploy.ps1
  ci/generate-auth-token.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.android.firebase.test.yaml
  ci/nightly.gen.auth.token.yaml
  ci/nightly.ios.firebase.test.yaml
  ci/nightly.template.steps.yaml
  ci/run-firebase-test.py
  ci/setup-and-build.ps1
  ci/setup-and-build.sh
  ci/slack-notify.ps1
Labels: jira/UNR, size/XXL

#211 Fix Spawn Emitter warnings for Linux Simplayer clients
  Game/Content/Blueprints/Weapons/BP_InstantWeapon.uasset
  Game/Content/Blueprints/Weapons/BP_ProjectileWeapon.uasset
  Game/Content/Blueprints/Weapons/Grenades/BP_Projectile.uasset
  Game/Content/VFX/BP_BulletTracer.uasset
Labels: jira/UNR, size/XS

#210 UNR-3998 Fix 4.25 Android file name error and modify some comments
  .buildkite/nightly.steps.yaml
  ci/change-runtime-settings.py
  ci/deploy.ps1
  ci/generate-auth-token.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.android.firebase.test.yaml
  ci/nightly.gen.auth.token.yaml
  ci/nightly.ios.firebase.test.yaml
  ci/nightly.template.steps.yaml
  ci/run-firebase-test.py
  ci/setup-and-build.ps1
Labels: jira/UNR, size/M

#212 Bind OnDeath delegate that calls Respawn for Simplayer character earlier
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
  Game/Content/Controllers/BP_SimulatedPlayerAIController.uasset
Labels: jira/UNR, size/XS

#215 UNR-4072 - Removed files from In-Game Tutorial Maps folder
  Game/Content/InGameTutorial/Maps/Map05_Offloading.umap
  Game/Content/InGameTutorial/Maps/Offloading/MultiWorkerSettings.uasset
  Game/Content/InGameTutorial/Maps/Offloading/NewBlueprint.uasset
  Game/Content/InGameTutorial/Maps/Offloading/SingleServerLBStrategy.uasset
Labels: jira/UNR, size/XS

#202 MBL-112 improved mobile controls
  Game/Config/DefaultInput.ini
  Game/Content/Characters/BP_FPS_Character.uasset
  Game/Content/UI/TouchControls/BP_TouchControls.uasset
  Game/Content/UI/TouchControls/BTN_ads.uasset
  Game/Content/UI/TouchControls/BTN_crouch.uasset
  Game/Content/UI/TouchControls/BTN_fire.uasset
  Game/Content/UI/TouchControls/BTN_jump.uasset
  Game/Content/UI/TouchControls/BTN_movement-control.uasset
  Game/Content/UI/TouchControls/BTN_movement.uasset
  Game/Content/UI/TouchControls/BTN_sprint.uasset
  Game/Source/GDKShooter/GDKShooter.Build.cs
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Private/UI/TouchControls.cpp
  Game/Source/GDKShooter/Public/Controllers/GDKPlayerController.h
  Game/Source/GDKShooter/Public/UI/TouchControls.h
Labels: jira/MBL, size/XXL

#217 Various fixes for the ExampleProject
  Game/Content/Blueprints/LoadBalancing/BP_VerboseSpatialDebugger.uasset
  Game/Content/GameMode/BP_DeathmatchGameMode.uasset
  Game/Content/GameMode/BP_GymGameState.uasset
  Game/Content/InGameTutorial/Maps/Map02_Components.umap
  Game/Content/InGameTutorial/Maps/Map03_RPCs.umap
  Game/Content/InGameTutorial/Maps/Map04_MulticastRPCs.umap
  Game/Content/InGameTutorial/Maps/Map06_SimulatedPlayers.umap
Labels: jira/no-ticket, size/XS

#216 UNR-3894 Migrate Slack-Notify step from Windows agent to Linux agent
  .buildkite/nightly.steps.yaml
  ci/generate-auth-token.ps1
  ci/slack-notify.ps1
  ci/slack-notify.py
Labels: jira/UNR, size/L
