Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-06, with the labels that each got.

#160 make sure all maps get cooked
  Game/Config/DefaultGame.ini
Labels: jira/no-ticket, size/S

#164 [UNR-3398] Control mode NPC Guards
  DeployGame.bat
  Game/Content/AI/BB_NPC.uasset
  Game/Content/AI/BB_Wander.uasset
  Game/Content/AI/BT_Wander.uasset
  Game/Content/Blueprints/BP_ControlPoint.uasset
  Game/Content/Blueprints/MapBuilder/Tiles/Misc/BP_Tile_Structure_Courtyard_A.uasset
  Game/Content/Blueprints/NPCs/BB_NPC.uasset
  Game/Content/Blueprints/NPCs/BTService_FireAtTarget.uasset
  Game/Content/Blueprints/NPCs/BTTask_ClearBlackboardValue.uasset
  Game/Content/Blueprints/NPCs/BTTask_FindPatrolPoint.uasset
  Game/Content/Blueprints/NPCs/BTTask_ScanForEnemies.uasset
  Game/Content/Blueprints/NPCs/BTTask_TetheredMoveTo.uasset
  Game/Content/Blueprints/NPCs/BTTask_UnocupyPatrolPoint.uasset
  Game/Content/Blueprints/NPCs/BT_NPC.uasset
  Game/Content/Blueprints/NPCs/Character_NPC.uasset
  Game/Content/Blueprints/NPCs/NPCSpawner.uasset
  Game/Content/Blueprints/NPCs/NPCTraceProvider.uasset
  Game/Content/Blueprints/NPCs/NPC_Controller.uasset
  Game/Content/Blueprints/NPCs/PatrolPoint.uasset
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/Player/Animations/AnimationBlueprints/CH_Robot_AnimBlueprint.uasset
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/Controllers/BP_SimulatedPlayerAIController.uasset
  Game/Content/GameMode/BP_ControlGameState.uasset
  Game/Content/GameMode/BP_GDKShooterGameInstance.uasset
  Game/Content/GameMode/BP_TeamDeathmatchGameState.uasset
  Game/Content/Maps/Control_Medium.umap
  Game/Content/Maps/Control_Small.umap
  Game/Content/UI/Blueprints/BP_RespawnMenu.uasset
  Game/Content/UI/Blueprints/BP_TeamDeathmatch_LoginScreen.uasset
  Game/Source/GDKShooter/Private/Characters/Components/HealthComponent.cpp
  Game/Source/GDKShooter/Private/Controllers/Components/ControllerEventsComponent.cpp
  Game/Source/GDKShooter/Private/Controllers/Components/TeamSettingComponent.cpp
  Game/Source/GDKShooter/Private/GDKShooterFunctionLibrary.cpp
  Game/Source/GDKShooter/Public/Characters/Components/HealthComponent.h
  Game/Source/GDKShooter/Public/Controllers/Components/TeamSettingComponent.h
  Game/Source/GDKShooter/Public/GDKShooterFunctionLibrary.h
Labels: jira/UNR, size/M

#173 Bugfix/UNR-3549 timer issue with squid
  Game/Source/GDKShooter/Private/Game/Components/TimerComponent.cpp
Labels: jira/UNR, size/XS

#174 [UNR-3655] Remove verbose debugger by default
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/UNR, size/XS

#172 Update pinned runtime and templates
  DeployGame.bat
  ci/deploy.ps1
  spatial/default_launch.json
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: jira/no-ticket, size/XS

#182 UNR-3402: Fix code indentation
  Game/Source/GDKShooter/Public/Characters/Components/EquippedComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/FirstPersonTraceProvider.h
  Game/Source/GDKShooter/Public/Characters/Components/GDKMovementComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/HealthComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/MetaDataComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/ShootingComponent.h
  Game/Source/GDKShooter/Public/Characters/Components/TeamComponent.h
  Game/Source/GDKShooter/Public/Characters/GDKCharacter.h
  Game/Source/GDKShooter/Public/Controllers/Components/ControllerEventsComponent.h
  Game/Source/GDKShooter/Public/Controllers/Components/TeamSettingComponent.h
  Game/Source/GDKShooter/Public/Controllers/GDKPlayerController.h
  Game/Source/GDKShooter/Public/Deployments/DeploymentSnapshotTemplate.h
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchScoreComponent.h
  Game/Source/GDKShooter/Public/Game/Components/DeathmatchSpawnerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/LobbyTimerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/MatchStateComponent.h
  Game/Source/GDKShooter/Public/Game/Components/PlayerCountingComponent.h
  Game/Source/GDKShooter/Public/Game/Components/PlayerPublisher.h
  Game/Source/GDKShooter/Public/Game/Components/ScorePublisher.h
  Game/Source/GDKShooter/Public/Game/Components/SpatialSessionStateComponent.h
  Game/Source/GDKShooter/Public/Game/Components/SpawnRequestPublisher.h
  Game/Source/GDKShooter/Public/Game/Components/TeamSpawnerComponent.h
  Game/Source/GDKShooter/Public/Game/Components/TimerComponent.h
  Game/Source/GDKShooter/Public/GameFramework/CrossServerPawn.h
  Game/Source/GDKShooter/Public/Phases/IPhaseActivated.h
  Game/Source/GDKShooter/Public/Phases/PhasedPainCausingVolume.h
  Game/Source/GDKShooter/Public/UI/GDKWidget.h
  Game/Source/GDKShooter/Public/Weapons/Holdable.h
  Game/Source/GDKShooter/Public/Weapons/ITraceProvider.h
  Game/Source/GDKShooter/Public/Weapons/InstantWeapon.h
  Game/Source/GDKShooter/Public/Weapons/Projectile.h
  Game/Source/GDKShooter/Public/Weapons/ProjectileWeapon.h
  Game/Source/GDKShooter/Public/Weapons/Weapon.h
Labels: jira/UNR, size/XXL

#180 Set Controls maps as default
  Game/Config/DefaultEngine.ini
Labels: jira/no-ticket, size/XS

#183 Fix simplayers spawning logic
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/Maps/Control_Small.umap
Labels: jira/UNR, size/XS

#184 [UNR-3719] Fix runtime version in batch scripts
  DeployGame.bat
  LaunchSpatial.bat
Labels: jira/UNR, size/XS

#187 [UNR-3733] Update scripts to runtime 0.4.3
  DeployGame.bat
  LaunchSpatial.bat
Labels: jira/UNR, size/XS

#188 [UNR-3731][MS] Fix SimPlayer error spam "ServerMove: TimeStamp expired"
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
Labels: jira/UNR, size/XS
