Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-11, with the labels that each got.

#225 Feature/upgrade to v15
  Game/Source/GDKShooter/Private/Deployments/DeploymentSnapshotTemplate.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentSnapshotTemplate.h
  spatial/spatialos.json
  spatial/workers/deployment-manager/spatialos.DeploymentManager.worker.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/M

#227 bugfix/UNR-3289/Fix spatial commands on workers on native windows
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/UNR, size/S

#226 [UNR-4495] Update queue to use new FastBuild v1.02
  ci/generate-auth-token.ps1
  ci/generate-pipeline-steps.sh
  ci/nightly.android.firebase.test.yaml
  ci/nightly.gen.auth.token.yaml
  ci/nightly.ios.firebase.test.yaml
  ci/nightly.template.steps.yaml
Labels: jira/UNR, size/S

#228 Fix issue of blank in the end of version
  ci/generate-pipeline-steps.sh
Labels: jira/no-ticket, size/S

#230 Update runtime version to 15 preview-4 for nightly build
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/XS

#229 Remove worker attributes
  spatial/spatialos.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
  spatial/workers/unreal/spatialos.UnrealClient.worker.json
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/S
