Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-02, with the labels that each got.

#95 Hiding quit button for Android
  Game/Content/UI/Blueprints/BP_QuitButton.uasset
Labels: jira/no-ticket, size/XS

#96 Fixing players not appearing on iOS
  Game/Content/Base/MasterMaterials/M_Spatial_Asset_MASTER.uasset
Labels: jira/no-ticket, size/XS

#98 Decrementing player count when player disconnects.
  Game/Content/GameMode/BP_PlayerState.uasset
  Game/Source/GDKShooter/Private/Controllers/GDKPlayerController.cpp
  Game/Source/GDKShooter/Public/Controllers/GDKPlayerController.h
  Game/Source/GDKShooter/Public/Game/Components/PlayerPublisher.h
Labels: jira/UNR, size/S

#97 Make standalone client target Open Match
  Game/Config/DefaultEngine.ini
  Game/Config/DefaultGame.ini
  Game/Config/DefaultSpatialGDKEditorSettings.ini
  Game/Content/UI/Blueprints/Deployments/BP_HUD_Deployments.uasset
  Game/Content/UI/Blueprints/Deployments/BP_LobbyScreen_OpenMatch.uasset
  Game/Source/GDKShooter/GDKShooter.Build.cs
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
  LaunchClient.bat
  spatial/workers/unreal/spatialos.UnrealWorker.worker.json
Labels: jira/no-ticket, size/L

#100 [UNR-2417][MS] Fixing some warnings in cloud deployment to do with a "None" component.
  Game/Content/Characters/BP_Base_Character.uasset
  Game/Content/Characters/BP_FPS_Character.uasset
Labels: jira/UNR, size/XS

#94 MBL-19 Remove some hard coded logics in ADeploymentsPlayerController.
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
Labels: jira/MBL, size/M

#101 [UNR-2864] [MBL-4] Android CI
  .buildkite/nightly.steps.yaml
  ci/nightly.template.steps.yaml
  ci/setup-and-build.ps1
Labels: jira/UNR, size/M

#103 Update the ExampleProject to use the new ConnectionManager flow
  Game/Config/DefaultSpatialGDKSettings.ini
  Game/Source/GDKShooter/Private/Deployments/DeploymentsPlayerController.cpp
  Game/Source/GDKShooter/Public/Deployments/DeploymentsPlayerController.h
Labels: jira/UNR, size/S

#106 adding fastlane config file
  fastlane/Matchfile
Labels: jira/no-ticket, size/XS

#104 [UNR-2978][MS] Removing building of SimPlayers from BuildWorker.bat
  BuildProject.bat
Labels: jira/UNR, size/XS
