Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-01, with the labels that each got.

#87 [UNR-2641] Make the Example project compatible with 4.22
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/UI/Blueprints/BP_QuitButton.uasset
  ci/slack-notify.ps1
Labels: jira/UNR, size/XS

#89 [UNR-1715][MS] Fix for error messages being displayed when character is killed.
  Game/Content/Characters/BP_Base_Character.uasset
Labels: jira/UNR, size/XS

#88 UNR-2523 Fixes for the rotation, jumping and firing for the example project
  Game/Content/Characters/BP_FPS_Character.uasset
  Game/Source/GDKShooter/Private/Characters/GDKCharacter.cpp
  Game/Source/GDKShooter/Public/Characters/Components/EquippedComponent.h
Labels: jira/UNR, size/XS

#90 [UNR-2731] Disable example project CI on 4.22
  ci/generate-pipeline-steps.sh
Labels: jira/UNR, size/XS

#91 Updating simulated player worker config
  spatial/spatialos.json
  spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
Labels: jira/no-ticket, size/S

#92 Bugfix/gdk worker types
  Game/Source/GDKShooter/Private/Game/Components/SpatialSessionStateComponent.cpp
Labels: jira/no-ticket, size/XS
