Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-04, with the labels that each got.

#115 Enabling MacOS & iOS CI for example project
  .buildkite/nightly.steps.yaml
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
  ci/setup-and-build.sh
Labels: jira/no-ticket, size/L

#133 Check schema gen exit code
  ci/setup-and-build.ps1
Labels: jira/no-ticket, size/S

#135 Symlink the UnrealEngine to a static location
  ci/setup-and-build.ps1
Labels: jira/no-ticket, size/S

#134 Fixing SimPlayer. Adding back in reverted fix.
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_DeathmatchGameMode.uasset
Labels: jira/no-ticket, size/XS

#128 [UNR-3142][MS] Changing config setting bPreventAutoConnectWithLocator
  Game/Config/DefaultEngine.ini
Labels: jira/UNR, size/XS

#137 [UNR-3247][MS] Fixing not player spawning in crash gym.
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
Labels: jira/UNR, size/XS

#138 Update defaults
  Game/Config/DefaultSpatialGDKSettings.ini
Labels: jira/no-ticket, size/XS

#140 Added BP_DeathmatchGameInstance to show delegate usage
  Game/Config/DefaultEngine.ini
  Game/Content/GameMode/BP_GDKShooterGameInstance.uasset
Labels: jira/UNR, size/XS

#141 updating spatialos.json
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS
