Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2020-07, with the labels that each got.

#186 Bugs/UNR 3402 fix match restart
  Game/Content/Controllers/BP_GDK_PlayerController.uasset
  Game/Content/GameMode/BP_ControlGameState.uasset
  Game/Content/GameMode/BP_TeamDeathmatchGameState.uasset
  Game/Content/UI/Blueprints/Scores/BP_ResultsScreen.uasset
  Game/Content/UI/Blueprints/Scores/BP_ScoreTableWidget.uasset
  Game/Content/UI/Blueprints/Scores/BP_TeamScoreTable.uasset
Labels: jira/UNR, size/XS

#190 [UNR-3078] Delete default launch
  spatial/default_launch.json
Labels: jira/UNR, size/M

#185 Better branch detection for CI in the example project
  ci/generate-pipeline-steps.sh
  ci/nightly.template.steps.yaml
Labels: jira/no-ticket, size/S

#196 Fix APlayerState::PlayerId deprecation warnings
  Game/Source/GDKShooter/Private/Characters/Components/HealthComponent.cpp
  Game/Source/GDKShooter/Private/Controllers/Components/ControllerEventsComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/DeathmatchScoreComponent.cpp
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchScoreComponent.cpp
Labels: jira/no-ticket, size/M

#203 [UNR-3924][MS] Fixing missing score UI info
  Game/Content/UI/Blueprints/Scores/BP_TeamScoreTable.uasset
Labels: jira/UNR, size/XS

#204 Fix crash due to spawner not being initialized
  Game/Source/GDKShooter/Private/Game/Components/TeamDeathmatchSpawnerComponent.cpp
Labels: jira/UNR, size/XS

#206 Pass -nocompile to skip compiling automation scripts
  ci/setup-and-build.ps1
Labels: jira/UNR, size/XS
