Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2021-03, with the labels that each got.

#250 UNR-4915 Fix/limit default client permission
  spatial/one_worker_test.json
  spatial/two_worker_test.json
Labels: jira/UNR, size/M

#251 UNR-5163 Feature/upgrade to runtime 15.0.1
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/UNR, size/XS

#252 UNR-4844: Removed StaticComponentView usages
  Game/Source/GDKShooter/Private/Game/Components/SpatialSessionStateComponent.cpp
Labels: jira/UNR, size/S

#253 Add new CI system in parallel
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/S
