Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2021-01, with the labels that each got.

#241 Upgrade preview 7
  .buildkite/nightly.steps.yaml
  spatial/spatialos.json
Labels: jira/PREVIEW, size/XS

#242 [UNR-4795] Reset server movement data on local client possession.
  Game/Content/Characters/BP_SimulatedPlayerCharacter.uasset
  Game/Source/GDKShooter/Private/Characters/GDKCharacter.cpp
  Game/Source/GDKShooter/Public/Characters/GDKCharacter.h
Labels: jira/UNR, size/XS

#243 Update to preview 8
  .buildkite/nightly.steps.yaml
  spatial/spatialos.json
Labels: jira/PREVIEW, size/XS

#239 …
  Game/Config/DefaultEngine.ini
  Game/Content/GameMode/BP_GDKShooterGameInstance.uasset
Labels: jira/no-ticket, size/XS

#246 Prevent values being left in PatrolPoint::OccupiedBy
  Game/Content/Blueprints/NPCs/BTTask_UnocupyPatrolPoint.uasset
  Game/Content/Blueprints/NPCs/BT_NPC.uasset
Labels: jira/UNR, size/XS

#247 Upgrade to 15.0.0
  .buildkite/nightly.steps.yaml
  DeployGame.bat
  LaunchSpatial.bat
  spatial/spatialos.json
Labels: jira/no-ticket, size/XS
