Repository spatialos/UnrealGDKExampleProject, pull requests merged in 2021-04, with the labels that each got.

#256 Disable Magic Leap plugins that were triggering WARNs
  Game/GDKShooter.uproject
Labels: jira/UNR, size/S

#257 Fix "The config file will be staged, but is not whitelisted or blacklisted" WARNs
  Game/Config/DefaultGame.ini
Labels: jira/UNR, size/XS

#258 Update nightly.steps.yaml
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/XS

#259 Fix labels and messages. Make new ci required.
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/XS

#260 Update nightly.steps.yaml
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/XS

#262 Update nightly.steps.yaml
  .buildkite/nightly.steps.yaml
Labels: jira/no-ticket, size/XS

#265 Delete LaunchSpatial.bat
  LaunchSpatial.bat
Labels: jira/UNR, size/XS
